theme: jekyll-theme-minimal

# Site settings
title: "Myc's HOME"
description: 'Share my life and work'


# Author settings
author: Myc # add your name
author-pic: myc.jpg # a picture of you
about-author: '' # a brief description of you
