theme: jekyll-theme-minimal

# Site settings
title: "Myc's HOME"
description: 'Share my life and work'
permalink: ':title:output_ext' # how the permalinks will behave


# Author settings
author: Myc # add your name
author-pic: './assets/myc.jpg' # a picture of you
about-author: '' # a brief description of you
